### ISSUE TITLE
This project should not include its own copy of Polymer.

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/polymer_interop#3]
This will cause two copies of Polymer to be downloaded and run, which can easily cause subtle bugs as Polymer assumes it will only load once.

One easy to imagine scenario is that a user of paper-elements transitively loads a newer version of Polymer, which has changed some private internal APIs. Then this project loads an older version of Polymer which attempts to use the older internal APIs and fails.

What ever happened to the proposal to allow pub to integrate with 3rd party package managers? The best option here, IMO, is to say that this package depends on the `Polymer/polymer` Bower package.

**Comment by jakemac53** [comment]
This is the canonical package for polymer now, the polymer package uses this package. This is primarily just to allow usage of the core/paper (now iron/etc) elements without using polymer dart.

@munificent can you comment on bower integration? I do agree that would be ideal here.

**Comment by munificent** [comment]
> What ever happened to the proposal to allow pub to integrate with 3rd party package managers?

Nothing, really. From feedback from our customers and users, it hasn't seemed like a very high priority, so we've been focusing on other things.
