### ISSUE TITLE
Make domInnerHtml available to Dart

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_interop#35]
https://github.com/Polymer/polymer/blob/master/src/lib/dom-innerHTML.html

**Comment by jakemac53** [comment]
Is there a difference between this and `new PolymerDom(node).innerHtml`?

**Comment by zoechi** [comment]
I didn't think about too much what this function does but I'm pretty sure it's quite different. It's used by the PolymerElements examples. I ported it to Dart as a workaround, but If the Polymer.js team thinks it's worth being added to the API it might be worth to make it available to Polymer.dart as well. Did you take a look at the code linked above?

**Comment by jakemac53** [comment]
The only place I see it being used though is inside the `innerHTML` getter for `Polymer.dom` https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/lib/dom-api.html#L732.

**Comment by jakemac53** [comment]
I have a feeling its not really intended to be a public api? It isn't documented anywhere, and accessing it is weird `Polymer.domInnerHTML.getInnerHtml(...)`

**Comment by zoechi** [comment]
I guess this can be closed. I'll reopen if I necessary.
