### ISSUE TITLE
[0.2.0-dev] various issues with PolymerDom class

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/polymer_interop#4]
I noted various issues with the PolymerDom class here:
https://github.com/dart-lang/polymer_interop/blob/0.2.0-dev/lib/polymer_interop.dart

For example, childNodes and and parentNode have setters, while they are readonly. The `classes` getter is marked as a `List<String>` while it is actually a JsObject with methods like, `add, remove` and `toggle`. There are also a couple of properties/methods missing. 

I understand this a dev branch, just thought I could maybe help a bit out, would you appreciate a PR?

**Comment by devoncarew** [comment]
@jakemac53, @kasperpeulen has been very helpful on dartpad (https://github.com/dart-lang/dart-pad/graphs/contributors) :) He recently did a lot of work to upgrade our JS polymer elements from 0.5 to 1.0.

**Comment by jakemac53** [comment]
A pr would be great, this is definitely a WIP, it pretty much just has whatever was needed to get todomvc working :).

**Comment by jakemac53** [comment]
fixed in https://github.com/dart-lang/polymer_interop/pull/5
