### ISSUE TITLE
analyzer 0.27.3

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/polymer_interop#44]
Trying to upgrade to `analyzer` 0.27.3 gives the following error when `pub get` is issued:

```
NoSuchMethodError: incorrect number of arguments passed to method named 'SdkAnalysisContext'
Receiver: Type: class 'SdkAnalysisContext'
Tried calling: SdkAnalysisContext(...)
Found: SdkAnalysisContext(AnalysisOptions)
    $include: '**/*_test.*'
    ^^^^^^^^^^^^^^^^^^^^^^^^
Error on line 23, column 5 of .../polymer_interop-1.0.0-rc.8/pubspec.yaml: Error loading transformer: No constructor 'SdkAnalysisContext' with matching arguments declared in class 'SdkAnalysisContext'.
```

Not sure if this is a `polymer_interop` issue or rather an `analyzer` one...

**Comment by jakemac53** [comment]
I can't repro this error, when I do a pub upgrade I get analyzer 0.27.4, and if I fix it to 0.27.3 I don't see any errors.

Can you consistently repro this?

**Comment by dam0vm3nt** [comment]
K, I'll try to make it

Il mar 9 ago 2016, 20:06 Jacob MacDonald notifications@github.com ha
scritto:

**Comment by dam0vm3nt** [comment]
Probably it was something with my setup I guess. Cleaning everything made this disappear.
