### ISSUE TITLE
Update PolymerProxyMixin class.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer_interop#6]
This should have everything here https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html

**Comment by kasperpeulen** [comment]
@jakemac53 here is some detailed api for the Polymer.Base class:
http://polymer.github.io/polymer/

**Comment by jakemac53** [comment]
ah nice thanks

**Comment by jakemac53** [comment]
Also, the array modification apis should most likely be translated to the dart list equivalents, see https://github.com/dart-lang/polymer-dart/blob/0.17-0-dev-interop-reverse/lib/src/common/polymer_mixin.dart#L40 for an example.

**Comment by jakemac53** [comment]
As mentioned in the bug I linked here, this class should probably be renamed to PolymerBase as well.

**Comment by jakemac53** [comment]
done
